module.exports = {
    type: 'Model',
    menuName: '3D Model',
    items: [
        'Mario',
        'Rabbid Luigi',
        'Rabbid Peach',
        'Garden Ziggy',
        'Sunflower',
        'Toadette',
        'Toad Friends',
        'White Rabbids',
        'Garden Hopper',
        'Pirabbid Plant',
        'Luigi',
        'Garden Smasher',
        'Rabbid Kong',
        'Sherbet Ziggy',
        'Sherbet Hopper',
        'Sherbet Smasher',
        'Sherbet Supporter',
        'Blizzy',
        'Sandy',
        'Rabbid Mario',
        'Sherbet Buckler',
        'Peach',
        'Icicle Golem',
        'Spooky Ziggy',
        'Spooky Supporter',
        'Spooky Peek-a-Boo',
        'Spooky Hopper',
        'Spooky Smasher',
        'Calavera',
        'Rabbid Yoshi',
        'Spooky Valkyrie',
        'Spooky Buckler',
        'Phantom',
        'Lava Ziggy',
        'Lava Hopper',
        'Lava Smasher',
        'Lava Valkyrie',
        'Lava Buckler',
        'Lava Supporter',
        'Lava Peek-a-Boo',
        'Mecha Jr.',
        'Yoshi',
        'Bwario',
        'Bwaluigi',
        'Lava Queen',
        'MegaDragonBowser',
        'MegaBug',
        'Spawny'
    ]
};
