module.exports = {
    type: 'Artwork',
    menuName: 'Artwork',
    items: [
        'Leafy World',
        'Baffling Blocks',
        'Geyser Goombas',
        'Ancient Gardens V0',
        'Piping Session',
        'Rabbid Kong',
        'Exotic Ford',
        'Banzai Bill',
        'Wrecking Smasher',
        'Archaeo Site',
        'Archaeo Details',
        'Hieroglyphic',
        'Giant Skeleton',
        'The Giant Fridge',
        'Spooky Ziggy',
        'Swamp House',
        'Odd Fountain',
        'The Spooky Swamp',
        'Spooky Valkyrie',
        'Eerie Little Square',
        'Operate Theatre',
        'The Mine',
        'Smithy',
        'Mecha Prototype',
        'Mushroom Tunnel',
        'Lava Boss V0',
        'Bwaaahr Machines',
        `Bowser's Castle`
    ]
};
