module.exports = {
    type: 'Music',
    menuName: 'Soundtrack',
    items: [
        'Prologue',
        'Grand Opening',
        `Beep-O's Lesson`,
        'Ziggies Battle',
        'The Waterfall Puzzle',
        'A Towering View',
        'Ancient Gardens',
        'Through the Lawns',
        'Mystic Journey',
        'Mystic Battle',
        'The Midboss Theme',
        'Hoppers!',
        'At the Towers Feet',
        `Tower's Theme 1`,
        `Tower's Puzzle`,
        `Tower's Theme 2`,
        `Rabbid Kong's Theme`,
        'A Song of Ice and Desert',
        'Ice of Sherbet Desert',
        'In the Heat of the Battle',
        'Hot Start, Cold Finish',
        'Cold Start, Hot Finish',
        'In the Cold of the Battle',
        `Icicle Golem's Theme`,
        'Spooky Village',
        'Spooky Skirmish',
        'Abbey Ruins',
        'Lost in the Swamp',
        'The Swamp Battle',
        'Combat in the Cemetery',
        'A Stroll in the Cemetery',
        `Phantom's Theme`,
        'Into the Pit',
        'The Forge Battle',
        'Exploring the Mine',
        'Heart of Darkness',
        'Theme with no Name 1',
        'Theme with no Name 2',
        'Theme with no Name 3',
        `Bowser's theme`
    ]
};
